export const dummyProjects = [
    {
      title: "Tree Planting Initiative",
      description: "A project focused on planting trees in urban areas.",
      endDate: "2024-12-31",
      status: "Active",
      type: "Tree",
      tags: ["environment", "community"],
    },
    {
      title: "Water Conservation Project",
      description: "Initiatives to conserve water in agricultural areas.",
      endDate: "2024-06-30",
      status: "Completed",
      type: "Water",
      tags: ["water", "agriculture"],
    },
    {
      title: "Land Restoration Program",
      description: "Efforts to restore degraded land to enhance biodiversity.",
      endDate: "2024-11-15",
      status: "Active",
      type: "Land",
      tags: ["restoration", "biodiversity"],
    },
    {
      title: "Urban Green Spaces",
      description: "Creating parks and green areas in city landscapes.",
      endDate: "2025-01-20",
      status: "Active",
      type: "Tree",
      tags: ["urban", "parks"],
    },
    {
      title: "Rainwater Harvesting Project",
      description: "Implementing systems for rainwater collection.",
      endDate: "2024-09-10",
      status: "Completed",
      type: "Water",
      tags: ["rainwater", "conservation"],
    },
    {
      title: "Sustainable Farming Initiative",
      description: "Promoting sustainable practices in agriculture.",
      endDate: "2024-08-01",
      status: "Active",
      type: "Land",
      tags: ["sustainable", "farming"],
    },
    {
      title: "Coastal Cleanup Drive",
      description: "Cleaning up beaches and coastal areas.",
      endDate: "2024-05-25",
      status: "Active",
      type: "Water",
      tags: ["coastal", "cleanup"],
    },
    {
      title: "Wildlife Conservation Project",
      description: "Protecting endangered species and their habitats.",
      endDate: "2024-07-15",
      status: "Active",
      type: "Tree",
      tags: ["wildlife", "conservation"],
    },
    {
      title: "Community Garden Initiative",
      description: "Establishing community gardens for local food production.",
      endDate: "2025-03-30",
      status: "Planned",
      type: "Land",
      tags: ["community", "gardening"],
    },
    {
      title: "Plastic Waste Reduction Campaign",
      description: "Raising awareness and reducing plastic waste.",
      endDate: "2024-10-05",
      status: "Active",
      type: "Land",
      tags: ["plastic", "awareness"],
    },
  ];
  